<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.egzosn</groupId>
    <artifactId>pay-java-parent</artifactId>
    <packaging>pom</packaging>
    <version>${revision}</version>

    <name>Pay Java - Parent</name>
    <description>Pay Java Parent</description>
    <url>https://github.com/egzosn/pay-java-parent</url>
    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Egan</name>
            <email>egzosn@gmail.com</email>
            <url>https://github.com/egzosn</url>
        </developer>
        <developer>
            <name>Actinia</name>
            <email>hayesfu@qq.com</email>
            <url>https://github.com/Actinian</url>
        </developer>
        <developer>
            <name>zch</name>
            <email>zhangchenghui.dev@gmail.com</email>
            <url>https://github.com/objcoding</url>
        </developer>
        <developer>
            <name>hocgin</name>
            <email>hocgin@gmail.com</email>
            <url>https://github.com/hocgin</url>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:https://github.com/egzosn/pay-java-parent.git</connection>
        <developerConnection>scm:git:git@github.com:egzosn/pay-java-parent.git</developerConnection>
        <url>https://github.com/egzosn/pay-java-parent</url>
    </scm>


    <modules>
        <module>pay-java-common</module>
        <module>pay-java-web-support</module>
        <module>pay-java-ali</module>
        <module>pay-java-wx</module>
        <module>pay-java-wx-youdian</module>
        <module>pay-java-fuiou</module>
        <module>pay-java-union</module>
        <module>pay-java-payoneer</module>
        <module>pay-java-paypal</module>
        <module>pay-java-yiji</module>
        <module>pay-java-baidu</module>
<!--        <module>pay-java-demo</module>-->
    </modules>


    <properties>
        <revision>2.14.12</revision>
        <httpmime.version>4.5.4</httpmime.version>
        <log4j.version>1.2.17</log4j.version>
        <fastjson.version>1.2.83</fastjson.version>
        <zxing.version>3.3.1</zxing.version>
        <servlet-api.version>4.0.1</servlet-api.version>
        <bcprov-jdk15on.version>1.59</bcprov-jdk15on.version>
        <java.version>8</java.version>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <flatten-maven-plugin.version>1.1.0</flatten-maven-plugin.version>
    </properties>


    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>com.egzosn</groupId>
                <artifactId>pay-java-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.egzosn</groupId>
                <artifactId>pay-java-web-support</artifactId>
                <version>${revision}</version>
            </dependency>

            <!--httpcomponents-->
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpmime</artifactId>
                <version>${httpmime.version}</version>
            </dependency>
            <!--/httpcomponents-->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk15on</artifactId>
                <version>${bcprov-jdk15on.version}</version>
            </dependency>

            <!-- log4j  -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>1.7.30</version>
            </dependency>
            <!-- / log4j -->


            <dependency>
                <groupId>com.google.zxing</groupId>
                <artifactId>core</artifactId>
                <version>${zxing.version}</version>
            </dependency>

            <dependency>
                <groupId>javax.servlet</groupId>
                <artifactId>javax.servlet-api</artifactId>
                <scope>provided</scope>
                <version>${servlet-api.version}</version>
            </dependency>

        </dependencies>

    </dependencyManagement>
    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>
    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <!--                        <fork>true</fork>-->
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>
    <profiles>
        <profile>
            <id>local</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>proc</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>3.3.0</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>3.6.0</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>1.6</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.5.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>